INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('1','日','ニチ ジツ -','ひ -び','day, sun, Japan','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('2','一','イチ イツ ヒト.','ひと-','one','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('3','国','コク ク','','country','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('4','人','ジン ニン -','ひと -り','person','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('5','年','ネン ト','','year','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('6','大','ダイ タイ -オオ.イ','おお- おお.きい','large, big','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('7','十','ジュウ ジッ ジュッ','とお','ten','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('8','二','ニ ジ フタタ.','ふた ふた.つ','two','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('9','本','ホン モ','','book, present, main, true, real, counter for long things','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('10','中','チュウ アタ.','なか うち','in, inside, middle, mean, center','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('11','長','チョウ オ','なが.い','long, leader','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('12','出','シュツ スイ イ.ダ','で.る -で だ.す -だ.す い.でる','exit, leave','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('13','三','サン ゾウ ミッ.','み み.つ','three','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('14','時','ジ -ド','とき','time, hour','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('15','行','コウ ギョウ アン オコ.ナ','い.く ゆ.く -ゆ.き -ゆき -い.き -いき おこな.う','going, journey','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('16','見','ケン','み.る み.える み.せる','see, hopes, chances, idea, opinion, look at, visible','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('17','月','ゲツ ガツ ツ','','month, moon','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('18','後','ゴ コウ オク.レ','のち うし.ろ うしろ あと','behind, back, later','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('19','前','ゼン -マ','まえ','in front, before','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('20','生','セイ ショウ -','い.きる い.かす い.ける う.まれる う.まれ うまれ う.む お.う は.える は.やす き なま なま- な.る','life, genuine, birth','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('21','五','ゴ イツ.','いつ','five','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('22','間','カン ケン','あいだ ま あい','interval, space','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('23','上','ジョウ ショウ シャン ヨ.','うえ -うえ うわ- かみ あ.げる -あ.げる あ.がる -あ.がる あ.がり -あ.がり のぼ.る のぼ.り のぼ.','above, up','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('24','東','トウ ヒガ','','east','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('25','四','シ ヨ','よ よ.つ よっ.つ','four','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('26','今','コン キン イ','','now','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('27','金','キン コン ゴン -ガ','かね かな-','gold','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('28','九','キュウ ク ココノ.','ここの','nine','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('29','入','ニュウ ジュ ハイ.','い.る -い.る -い.り い.れる -い.れ','enter, insert','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('30','学','ガク マナ.','','study, learning, science','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('31','高','コウ タカ.メ','たか.い たか -だか たか.まる','tall, high, expensive','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('32','円','エン マロ.ヤ','まる.い まる まど まど.か','circle, yen, round','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('33','子','シ ス ツ','こ -こ','child, sign of the rat, 11PM-1AM, first sign of Chinese zodiac','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('34','外','ガイ ゲ','そと ほか はず.す はず.れる と','outside','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('35','八','ハチ ヨ','や や.つ やっ.つ','eight','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('36','六','ロク リク ム','む む.つ むっ.つ','six','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('37','下','カ ゲ オ.リ','した しも もと さ.げる さ.がる くだ.る くだ.り くだ.す -くだ.す くだ.さる お.ろす','below, down, descend, give, low, inferior','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('38','来','ライ タイ','く.る きた.る きた.す き.たす き.たる き','come, due, next, cause, become','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('39','気','キ ケ','いき','spirit, mind','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('40','小','ショウ','ちい.さい こ- お- さ','little, small','1','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('41','七','シチ ナ','なな なな.つ','seven','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('42','山','サン セン ヤ','','mountain','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('43','話','ワ','はな.す はなし','tale, talk','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('44','女','ジョ ニョ ニョウ','おんな','woman, female','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('45','北','ホク キ','','north','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('46','午','ゴ','うま','noon, sign of the horse, 11AM-1PM, seventh sign of Chinese zodiac','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('47','百','ヒャク ビャク モ','','hundred','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('48','書','ショ -ガ','か.く -が.き','write','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('49','先','セン マ.','さき','before, ahead, previous, future, precedence','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('50','名','メイ ミョウ -','な','name, noted, distinguished, reputation','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('51','川','セン カ','','stream, river','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('52','千','セン','','thousand','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('53','水','スイ','みず みず','water','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('54','半','ハン ナカ.','','half, middle, odd number, semi-, part-','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('55','男','ダン ナン','おとこ','male','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('56','西','セイ サイ ス ニ','','west, Spain','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('57','電','デン','','electricity','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('58','校','コウ キョ','','exam, school, printing, proof, correction','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('59','語','ゴ','かた.る かた.らう','word, speech, language','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('60','土','ド ト ツ','','soil, earth, ground, Turkey','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('61','木','ボク モク','き こ','tree, wood','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('62','聞','ブン モン','き.く き.こえる','hear, ask, listen','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('63','食','ショク ジキ ハ.','く.う く.らう た.べる','eat, food','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('64','車','シャ クル','','car','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('65','何','カ','なに なん なに- なん','what','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('66','南','ナン ナ ミナ','','south','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('67','万','マン バン ヨロ','','ten thousand','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('68','毎','マイ -ゴト.','ごと','every','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('69','白','ハク ビャク シロ.','しろ しら-','white','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('70','天','テン','あまつ あめ あま','heavens, sky, imperial','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('71','母','ボ','はは も','mama, mother','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('72','火','カ','ひ -び ほ-','fire','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('73','右','ウ ユウ ミ','','right','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('74','読','ドク トク トウ -ヨ.','よ.む','read','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('75','友','ユウ ト','','friend','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('76','左','サ シャ ヒダ','','left','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('77','休','キュウ','やす.む やす.まる やす.める','rest, day off, retire, sleep','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('78','父','フ','ちち','father','2','5');
INSERT INTO JAPANESE_CHARACTERS (id,kanji,onyomi,kunyomi,englishTranslation,subunit,jlptlevel) VALUES ('79','雨','ウ','あめ あま- -さめ','rain','2','5');